version: '3'

services:
  frontend:
    build: frontend
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    build: backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    environment:
      - PORT=8000
      - DB_URL=mongodb://mongo:27017
  mongo:
    image: mongo:4.2.6
    ports:
      - 27017:27017
      - 27018:27018
      - 27019:27019
    volumes:
      - ./data/db:/data/db